import { Mona_Sans } from "next/font/google";
import "./globals.css";


const monaSans = Mona_Sans({
  variable: '--font-mona-sans', // You can name this whatever you prefer, e.g., '--font-mona-sans'
  subsets: ['latin'],
  display: 'swap', // Recommended for performance
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
